language: cpp
os: linux
sudo: false

cache:
    apt: true
    directories:
        - "${TRAVIS_BUILD_DIR}/deps"

compiler:
    - clang
    - gcc

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise
            - llvm-toolchain-precise-3.7
        packages:
            - clang-3.7
            - gcc-5
            - g++-5
            - valgrind
            - libjpeg62-dev
            - libsndfile1-dev
            - libglew1.5
            - libglew1.5-dev
            - libfreetype6
            - libjpeg-turbo8
            - libjpeg8
            - libopenal-data
            - libopenal1
            - libxrandr2
            - libxrender1
            - libsoil1

before_install:
    # Get CMake 3
    - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
    - mkdir ${DEPS_DIR} ; cd ${DEPS_DIR}
    - |
      CMAKE_URL="http://www.cmake.org/files/v3.3/cmake-3.3.1-Linux-x86_64.tar.gz"
      mkdir cmake && travis_retry wget --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
      export PATH=${DEPS_DIR}/cmake/bin:${PATH}

    # Get SFML2
    - SFML_DIR="${DEPS_DIR}/sfml"
    - wget http://www.sfml-dev.org/files/SFML-2.3.2-linux-gcc-64-bit.tar.gz -O /tmp/sfml.tar.gz
    - tar -xvzf /tmp/sfml.tar.gz
    - mkdir ${SFML_DIR}
    - cp -r SFML-2.3.2/* ${SFML_DIR}

install:
    - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
    - if [ "$CXX" = "clang++" ]; then export CXX="clang++-3.7" CC="clang-3.7"; fi

before_script:
    - cd ${TRAVIS_BUILD_DIR}
    - ./init-repository.sh
    - mkdir build && cd build
    - cmake .. -DCMAKE_CXX_COMPILER=${COMPILER} -DCMAKE_BUILD_TYPE=WIP -DSFML_ROOT=${SFML_DIR}

script:
    - cd ${TRAVIS_BUILD_DIR}
    - cd build
    - make -j4 check